---
uip_creds:
  aws:
    enabled: false
    region: ""
    access_key_id: ""
    secret_access_key: ""
    session_token: ""
  azure:
    enabled: false
    tenant_id: ""
    client_id: ""
    client_secret: ""
    subscription_id: ""
  gcp:
    enabled: false
    project_id: ""
    service_account_token: ""
  openstack:
    enabled: false
    auth_url: ""
    username: ""
    password: ""
    project_id: ""
    user_domain_name: "Default"
    project_domain_name: "Default"
  vmware:
    enabled: false
    vcenter_url: ""
    username: ""
    password: ""
    validate_certs: false
