application_profiles:
  RedHat:
    default:
      java:
        expected_services:
          - my-java-app
        expected_packages:
          - java-17-openjdk
        expected_files:
          - /etc/my-java-app/application.yml
          - /opt/my-java-app/app.jar
        expected_commands:
          - "test -f /opt/my-java-app/app.jar"
          - "systemctl is-active my-java-app"
          - "java -version"

      python:
        expected_services:
          - my-python-app
        expected_packages:
          - python3
        expected_files:
          - /opt/my-python-app/app.py
          - /etc/my-python-app/config.yaml
        expected_commands:
          - "test -f /opt/my-python-app/app.py"
          - "python3 --version"
          - "systemctl is-active my-python-app"

    rhel8:
      java:
        expected_services:
          - my-java-appd
        expected_packages:
          - java-18-openjdk
        expected_files:
          - /etc/my-java-appd/application.yml
          - /opt/my-java-appd/app.jar
        expected_commands:
          - "test -f /opt/my-java-appd/app.jar"
          - "systemctl is-active my-java-appd"
          - "java -version"

      python:
        expected_services:
          - my-python3-app
        expected_packages:
          - python3
        expected_files:
          - /opt/my-python3-app/app.py
          - /etc/my-python3-app/config.yaml
        expected_commands:
          - "test -f /opt/my-python3-app/app.py"
          - "python3 --version"
          - "systemctl is-active my-python3-app"

  Ubuntu:
    default:
      python:
        expected_services:
          - my-python-app
        expected_packages:
          - python3
        expected_files:
          - /opt/my-python-app/app.py
          - /etc/my-python-app/config.yaml
        expected_commands:
          - "test -f /opt/my-python-app/app.py"
          - "python3 --version"
          - "systemctl is-active my-python-app"

    ubuntu22:
      python:
        expected_services:
          - my-python-appd
        expected_packages:
          - python3.10
        expected_files:
          - /opt/my-python-appd/app.py
          - /etc/my-python-appd/config.yaml
        expected_commands:
          - "test -f /opt/my-python-appd/app.py"
          - "python3 --version"
          - "systemctl is-active my-python-appd"

      java:
        expected_services:
          - my-java-app22
        expected_packages:
          - openjdk-17-jre-headless
        expected_files:
          - /opt/my-java-app22/app.jar
        expected_commands:
          - "test -f /opt/my-java-app22/app.jar"
          - "systemctl is-active my-java-app22"
          - "java -version"
