linux_upgrade_repo_expected_gpg_fingerprints_map:
  RedHat:
    - "AA:BB:CC:DD:EE:FF"
  Debian:
    - "11:22:33:44:55:66"
  Ubuntu:
    - "77:88:99:AA:BB:CC"
  SLES:
    - "DD:EE:FF:00:11:22"

linux_upgrade_repo_expected_tls_hosts_map:
  default:
    - artifactory.example.com
    - satellite.example.com

linux_upgrade_repo_expected_tls_fingerprints_map:
  default:
    artifactory.example.com: "AA:BB:CC:DD:EE:FF:11:22:33:44:55:66:77:88:99:AA:BB:CC:DD:EE:FF:11:22:33:44:55:66:77:88:99"
    satellite.example.com: "11:22:33:44:55:66:77:88:99:AA:BB:CC:DD:EE:FF:00:11:22:33:44:55:66:77:88:99:AA:BB:CC:DD:EE:FF"


linux_upgrade_repo_profiles_by_major_version:
  Ubuntu:
    "22":
      internal_profile: ubuntu22
    "24":
      internal_profile: ubuntu24
  RedHat:
    "8":
      internal_profile: rhel8
    "9":
      internal_profile: rhel9
