vmware:
  hostname: vcenter.example.local
  username: svc_linux_upgrade
  password: change_me

proxmox:
  api_host: proxmox.example.local
  api_user: root@pam
  api_password: change_me

openstack:
  cloud: prod

servicenow:
  url: https://servicenow.example.local
  username: svc_linux_upgrade
  password: change_me


jira:
  url: https://jira.example.local
  username: svc_linux_upgrade
  password: change_me
  token: ""
