galaxy_info:
  role_name: linux_upgrade
  author: IRIVEN GROUP
  description: Autonomous Linux major upgrade role
  min_ansible_version: "2.14"
  license: MIT
  platforms:
    - name: EL
      versions: ["7", "8", "9", "10"]
    - name: Debian
      versions: ["10", "11", "12", "13", "14"]
    - name: Ubuntu
      versions: ["18.04", "20.04", "22.04", "24.04", "25.04"]
    - name: SLES
      versions: ["10", "11", "12", "15"]
dependencies: []
