- name: Check gateway post-upgrade
  shell: "ping -c 2 {{ linux_upgrade_network_post_check_gateway }}"
  changed_when: false
  when:
    - linux_upgrade_network_post_checks_enabled | bool
    - linux_upgrade_network_post_check_gateway | length > 0

- name: Check expected network hosts post-upgrade
  shell: "getent hosts {{ item }}"
  loop: "{{ linux_upgrade_network_post_check_hosts }}"
  changed_when: false
  when:
    - linux_upgrade_network_post_checks_enabled | bool
    - linux_upgrade_network_post_check_hosts | length > 0

- name: Check expected network URLs post-upgrade
  uri:
    url: "{{ item }}"
    method: GET
    status_code: 200
    validate_certs: true
  loop: "{{ linux_upgrade_network_post_check_urls }}"
  when:
    - linux_upgrade_network_post_checks_enabled | bool
    - linux_upgrade_network_post_check_urls | length > 0

# Merged from network_deep_postchecks.yml
- name: Check bastion route
  shell: "ip route get {{ linux_upgrade_network_post_check_bastion }}"
  changed_when: false
  when:
    - linux_upgrade_network_post_checks_enabled | bool
    - linux_upgrade_network_post_check_bastion | length > 0

- name: Check gateway per interface
  shell: "ping -I {{ item }} -c 2 {{ linux_upgrade_network_post_check_gateway }}"
  loop: "{{ linux_upgrade_network_post_check_interfaces }}"
  changed_when: false
  when:
    - linux_upgrade_network_post_checks_enabled | bool
    - linux_upgrade_network_post_check_per_interface_gateway | bool
    - linux_upgrade_network_post_check_gateway | length > 0
    - linux_upgrade_network_post_check_interfaces | length > 0
