- name: Check application hooks file
  stat:
    path: "{{ linux_upgrade_application_hooks_file }}"
  register: _application_hooks_file
  when: linux_upgrade_hooks_enabled | bool

- name: Load application hooks
  include_vars:
    file: "{{ linux_upgrade_application_hooks_file }}"
    name: linux_upgrade_application_hooks_catalog
  when:
    - linux_upgrade_hooks_enabled | bool
    - _application_hooks_file.stat.exists | default(false)

- name: Execute application pre-stop hooks
  shell: "{{ item }}"
  loop: "{{ (linux_upgrade_application_hooks_catalog.application_hooks.pre_stop | default([])) if (linux_upgrade_application_hooks_catalog is defined) else [] }}"
  changed_when: true
  when:
    - linux_upgrade_hooks_enabled | bool
    - linux_upgrade_application_hooks_phase == 'pre'

- name: Execute application post-start hooks
  shell: "{{ item }}"
  loop: "{{ (linux_upgrade_application_hooks_catalog.application_hooks.post_start | default([])) if (linux_upgrade_application_hooks_catalog is defined) else [] }}"
  changed_when: true
  when:
    - linux_upgrade_hooks_enabled | bool
    - linux_upgrade_application_hooks_phase == 'post'

- name: Execute application healthchecks
  shell: "{{ item }}"
  loop: "{{ (linux_upgrade_application_hooks_catalog.application_hooks.healthcheck | default([])) if (linux_upgrade_application_hooks_catalog is defined) else [] }}"
  changed_when: false
  when:
    - linux_upgrade_hooks_enabled | bool
    - linux_upgrade_application_hooks_phase == 'post'
