- name: Ensure archive dir exists
  file:
    path: "{{ linux_upgrade_artifacts_archive_dir }}"
    state: directory
    mode: "0750"
  when: linux_upgrade_artifacts_retention_enabled | bool

- name: Purge old artifacts
  shell: "find {{ linux_upgrade_state_dir }} -type f -mtime +{{ linux_upgrade_artifacts_retention_days | int }} -print -delete"
  changed_when: true
  when: linux_upgrade_artifacts_retention_enabled | bool
