- name: Update ServiceNow specific record
  uri:
    url: "{{ linux_upgrade_servicenow_instance_url }}/api/now/table/{{ linux_upgrade_servicenow_table }}/{{ linux_upgrade_servicenow_sys_id }}"
    method: PATCH
    force_basic_auth: true
    user: "{{ linux_upgrade_servicenow_username }}"
    password: "{{ linux_upgrade_servicenow_password }}"
    body_format: json
    body:
      work_notes: "{{ linux_upgrade_itsm_result_comment if (linux_upgrade_itsm_result_comment | length > 0) else ('Upgrade status updated for ' ~ inventory_hostname) }}"
    status_code: [200]
  when:
    - linux_upgrade_itsm_backend_specific_enabled | bool
    - linux_upgrade_servicenow_instance_url | length > 0
    - linux_upgrade_servicenow_sys_id | length > 0

- name: Add Jira specific comment
  uri:
    url: "{{ linux_upgrade_jira_base_url }}/rest/api/2/issue/{{ linux_upgrade_jira_issue_key_specific }}/comment"
    method: POST
    force_basic_auth: true
    user: "{{ linux_upgrade_jira_username }}"
    password: "{{ linux_upgrade_jira_api_token }}"
    body_format: json
    body:
      body: "{{ linux_upgrade_itsm_result_comment if (linux_upgrade_itsm_result_comment | length > 0) else ('Upgrade status updated for ' ~ inventory_hostname) }}"
    status_code: [200,201]
  when:
    - linux_upgrade_itsm_backend_specific_enabled | bool
    - linux_upgrade_jira_add_comment_enabled | bool
    - linux_upgrade_jira_base_url | length > 0
    - linux_upgrade_jira_issue_key_specific | length > 0

- name: Transition Jira issue success
  uri:
    url: "{{ linux_upgrade_jira_base_url }}/rest/api/2/issue/{{ linux_upgrade_jira_issue_key_specific }}/transitions"
    method: POST
    force_basic_auth: true
    user: "{{ linux_upgrade_jira_username }}"
    password: "{{ linux_upgrade_jira_api_token }}"
    body_format: json
    body:
      transition:
        id: "{{ linux_upgrade_jira_transition_id_success }}"
    status_code: [200,204]
  when:
    - linux_upgrade_itsm_backend_specific_enabled | bool
    - linux_upgrade_jira_base_url | length > 0
    - linux_upgrade_jira_issue_key_specific | length > 0
    - linux_upgrade_jira_transition_id_success | length > 0
