- name: Run prechecks
  include_tasks: ../operations/prechecks.yml
  tags: [plan, prechecks]

- name: Write report
  template:
    src: report.json.j2
    dest: "{{ linux_upgrade_report_file }}"
    mode: "0640"
  tags: [plan]
