---
- name: Rollback Linux in-place upgrade
  hosts: linux
  become: true
  gather_facts: true
  roles:
    - role: uip_common
      tags:
        - always
        - uip_common
        - uip_rollback
    - role: uip_rollback
      tags:
        - uip_rollback
    - role: uip_report
      tags:
        - always
        - uip_report
        - uip_rollback
