- name: Run cluster pre-drain commands
  shell: "{{ item }}"
  loop: "{{ linux_upgrade_cluster_pre_drain_commands }}"
  changed_when: true
  when:
    - linux_upgrade_cluster_enabled | bool
    - linux_upgrade_cluster_phase == 'pre'

- name: Run cluster post-activate commands
  shell: "{{ item }}"
  loop: "{{ linux_upgrade_cluster_post_activate_commands }}"
  changed_when: true
  when:
    - linux_upgrade_cluster_enabled | bool
    - linux_upgrade_cluster_phase == 'post'

- name: Run cluster health checks
  shell: "{{ item }}"
  loop: "{{ linux_upgrade_cluster_healthcheck_commands }}"
  changed_when: false
  when:
    - linux_upgrade_cluster_enabled | bool
    - linux_upgrade_cluster_phase == 'post'
