- name: Ensure config dir exists
  file:
    path: "{{ linux_upgrade_config_dir }}"
    state: directory
    mode: "0750"

- name: Ensure state dir exists
  file:
    path: "{{ linux_upgrade_state_dir }}"
    state: directory
    mode: "0750"
