- name: Run middleware pre commands
  shell: "{{ item }}"
  loop: "{{ linux_upgrade_middleware_pre_commands }}"
  changed_when: true
  when:
    - linux_upgrade_middleware_enabled | bool
    - linux_upgrade_middleware_phase == 'pre'

- name: Run middleware post commands
  shell: "{{ item }}"
  loop: "{{ linux_upgrade_middleware_post_commands }}"
  changed_when: true
  when:
    - linux_upgrade_middleware_enabled | bool
    - linux_upgrade_middleware_phase == 'post'
