- name: Register RHEL via Satellite activation key
  shell: >
    subscription-manager register --force
    --activationkey={{ linux_upgrade_repo_profile.get('post', {}).get('satellite_activation_key', '') }}
    --org={{ linux_upgrade_satellite_org | default('Default_Organization') }}
  changed_when: true
  no_log: true
  when:
    - linux_upgrade_subscriptions_phase == 'post'
    - ansible_os_family == 'RedHat'
    - linux_upgrade_repo_profile.get('post', {}).get('satellite_activation_key', '') | length > 0

- name: Register SLES with regcode
  shell: "SUSEConnect -r {{ linux_upgrade_repo_profile.get('post', {}).get('suse_regcode', '') }}"
  changed_when: true
  no_log: true
  when:
    - linux_upgrade_subscriptions_phase == 'post'
    - ansible_os_family == 'Suse'
    - linux_upgrade_repo_profile.get('post', {}).get('suse_regcode', '') | length > 0
