- name: Create pending reboot flag
  file:
    path: "{{ linux_upgrade_pending_reboot_flag }}"
    state: touch
    mode: "0640"

- name: Execute upgrade on RHEL-like using leapp
  shell: |
    set -e
    leapp preupgrade || true
    leapp upgrade
  when: ansible_os_family == 'RedHat'
  register: _upgrade_result
  changed_when: true

- name: Execute upgrade on Debian
  shell: |
    set -e
    export DEBIAN_FRONTEND=noninteractive
    sed -i "s/{{ linux_upgrade_source_major_version }}/{{ linux_upgrade_target_major_version }}/g" /etc/apt/sources.list || true
    apt-get update
    apt-get -y dist-upgrade
  when: ansible_distribution == 'Debian'
  register: _upgrade_result
  changed_when: true

- name: Execute upgrade on Ubuntu
  shell: |
    set -e
    export DEBIAN_FRONTEND=noninteractive
    do-release-upgrade -f DistUpgradeViewNonInteractive
  when: ansible_distribution == 'Ubuntu'
  register: _upgrade_result
  changed_when: true

- name: Execute upgrade on SLES
  shell: |
    set -e
    zypper migration --non-interactive
  when: ansible_os_family == 'Suse'
  register: _upgrade_result
  changed_when: true
